version: '3.8'
services:
  spring-boot-app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - keycloak
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/my_db?currentSchema=wide_test
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      KEYCLOAK_SERVER_URL: http://keycloak:8080
      KEYCLOAK_REALM: master
      KEYCLOAK_RESOURCE: admin-cli
      KEYCLOAK_PUBLIC_CLIENT: true
      SERVER_PORT: 8000
    networks:
      - keycloak-network

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak-network

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    ports:
      - "8080:8080"
    command: start-dev
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_PORT: 5432
      DB_DATABASE: my_db
      DB_USER: root
      DB_PASSWORD: 1234
      KEYCLOAK_SERVER_URL: http://keycloak:8080
      KEYCLOAK_REALM: master
      KEYCLOAK_RESOURCE: admin-cli
      KEYCLOAK_EXTRA_ARGS: "-Dkeycloak.import=/opt/keycloak/data/import/"
    volumes:
      - keycloak_data:/opt/keycloak/data/import
    networks:
      - keycloak-network

volumes:
  postgres_data:
  keycloak_data:
    driver: local
networks:
  keycloak-network:
    driver: bridge
